name: volare_radiotalk
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.0

  # Widget
  pull_to_refresh: ^1.6.2
  photo_view: ^0.10.2
  webview_flutter: ^1.0.3
  # app_review: ^1.1.0+1
  image_picker: ^0.6.7+12
  image_cropper: ^1.3.1
  auto_size_text: ^2.1.0
  modal_progress_hud: ^0.1.3
  solid_bottom_sheet: ^0.1.9
  url_launcher: ^5.5.0
  dots_indicator: ^1.0.0
  extended_image: ^1.2.0
  bubble: ^1.1.9+1

  #calendar
  flutter_calendar_carousel: ^1.4.12

  # Functions
  intl: ^0.16.1
  devicelocale: ^0.2.3
  date_calc: ^0.1.1+3
  device_info: ^0.4.2+4
  synchronized: 2.2.0
  rxdart: ^0.24.1
  uuid: ^2.2.0
  stop_watch_timer: ^0.6.0+1
  package_info: 0.4.0+17
  flutter_swiper: ^1.1.6
  recorder_wav:
  flutter_sound:

  # QR code
  qr_code_scanner: 0.0.12
  qr_flutter: ^3.2.0

  # Permission
  permission_handler: ^5.0.1+1

  # Provider
  path_provider: ^1.6.11
  provider: ^4.3.1
  state_notifier:
  flutter_state_notifier:
  freezed_annotation:

  # logger
  simple_logger:

  # Local database
  shared_preferences: ^0.5.8

  # Algolia
  algolia: ^0.1.7

  # GoogleMap
  google_maps_flutter: ^1.0.5
  geolocator: ^6.1.0

  # Firebase
  flamingo: ^1.11.0
  firebase_core: ^0.5.2
  flamingo_annotation:
  # firebase_remote_config: ^0.4.1
  firebase_auth: ^0.18.2
  firebase_analytics: ^6.1.0
  # cloud_functions: ^0.6.0
  # firebase_crashlytics: ^0.1.4+1
  # firebase_messaging: ^7.0.0

  # pin code input
  pin_input_text_field: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic_mono:
  intl_translation:
  build_runner: ^1.10.1
  flamingo_generator: ^0.6.0
  freezed: ^0.12.1
  build_resolvers: ^1.3.10

dependency_overrides:
  intl: ^0.16.1

flutter:
  generate: true
  uses-material-design: true
  fonts:
    - family: Radiotalk
      fonts:
        - asset: assets/fonts/radiotalk.ttf
  assets:
    - assets/
    - assets/drawable/
    - assets/sample/