/// Flutter icons Imory
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Imory
///      fonts:
///       - asset: fonts/Imory.ttf
///
///
///
import 'package:flutter/widgets.dart';

class Imory {
  Imory._();

  static const _kFontFam = 'Imory';

  static const IconData imory_icon_border =
      IconData(0xe800, fontFamily: _kFontFam);
  static const IconData imory_icon_background =
      IconData(0xe801, fontFamily: _kFontFam);
}
